---
- hosts: all
  tasks:
  - name: Get Ubuntu codename
    shell: lsb_release -sc
    register: codename
  - name: Add docker apt repository
    apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{codename.stdout}} main" state=present
    sudo: yes
  - name: Install Docker and git is installed
    apt: pkg=docker-engine state=present update_cache=yes force=yes
    sudo: yes
  - name: Checkout the Docker scripts
    git: repo=https://github.com/taptipalit/video_streaming_ansible_docker_scripts.git dest=streaming_benchmark

- hosts: server
  tasks:
  - name: Build the server docker
    command: docker build -t streaming_server streaming_benchmark/docker_server
    sudo: yes
  - name: Run the server docker
    command: docker run -d -t --net=host -v /streaming_server:/streaming_server --privileged=true --name=streaming_server streaming_server
    sudo: yes

- hosts: clients
  tasks:
  - name: Build the client docker
    command: docker build -t streaming_client streaming_benchmark/docker_client
    sudo: yes
  - name: Run the client docker
    command: docker run -d -t --net=host -v /streaming_client:/streaming_client --privileged=true --name=streaming_client streaming_client
    sudo: yes
  - name: Run the bandwidth limiting script
    command: docker exec streaming_client /bw_setup.sh {{if}} {{ip_alias1}} {{ip_alias2}} {{ip_alias3}} {{ip_alias4}}
