---
- hosts: all
  tasks:
  - name: Get Ubuntu codename
    shell: lsb_release -sc
    register: codename
  - name: Add docker apt repository
    apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{codename.stdout}} main" state=present
    sudo: yes
  - name: Install Docker and git is installed
    apt: pkg=docker-engine state=present update_cache=yes force=yes
    sudo: yes
  - name: Checkout the Docker scripts
    git: repo=https://github.com/taptipalit/video_streaming_ansible_docker_scripts.git dest=streaming_benchmark
    ignore_errors: yes

- hosts: server
  tasks:
  - name: Stop any docker container named streaming_server
    command: sudo docker stop streaming_server
    sudo: yes
  - name: Remove any docker container named streaming_server
    command: sudo docker rm streaming_server
    sudo: yes
  - name: Build the server docker
    command: sudo docker build -t streaming_server streaming_benchmark/docker_server
    sudo: yes
  - name: Run the server docker
    command: sudo docker run -d -t --net=host -v /streaming_server:/streaming_server --privileged=true --name=streaming_server streaming_server
    sudo: yes

- hosts: clients
  tasks:
  - name: Stop any docker container named streaming_client_
    command: sudo docker stop streaming_client
    sudo: yes
  - name: Remove any docker container named streaming_client
    command: sudo docker rm streaming_client
    sudo: yes
  - name: Build the client docker
    command: sudo docker build -t streaming_client streaming_benchmark/docker_client
    sudo: yes
  - name: Run the client docker
    command: sudo docker run -d -t --net=host -v /streaming_client:/streaming_client --privileged=true --name=streaming_client streaming_client
    sudo: yes
  - name: Install the kernel sources
    command: apt-get install linux-source -y
    sudo: yes
  - name: Clone the httperf directory
    git: repo=https://github.com/luigirizzo/dummynet.git dest=dummynet
  - name: Build the dummynet
    command: chdir=dummynet make
  - name: Install dummynet
    command: chdir=dummynet cp ipfw/ipfw /usr/sbin/ipfw
    sudo: yes
  - name: Load the module
    command: insmod dummynet/kipfw-mod/ipfw_mod.ko
    sudo: yes
    ignore_errors: yes
  - name: Copy the bandwidth limiting script
    copy: src=bw_setup.sh dest=/streaming_client mode="a+x" 
    sudo: yes
  - name: Run the bandwidth limiting script
    command: sudo /streaming_client/bw_setup.sh {{if}} {{ip_alias1}} {{ip_alias2}} {{ip_alias3}} {{ip_alias4}}
