---
- hosts: all
  tasks:
  - name: Get Ubuntu codename
    command: lsb_release -sc
    register: codename
  - name: Add docker apt repository
    apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{codename.stdout}} main" state=present
    sudo: yes
  - name: Install Docker
    apt: pkg=docker-engine state=present update_cache=yes force=yes
    apt: pkg=git state=present update_cache=yes
    sudo: yes
  - name: Copy the scripts to destination host
    synchronize: src=./ dest=streaming_benchmark/

- hosts: server
  tasks:
  - name: Make sure server has 1TB free for videos in /streaming_server
    shell: mkdir -p /streaming_server && exit $(($(stat -f --format="%a*%S < 1000000000000" /streaming_server)))
  - name: Remove docker container named streaming_server if it exists
    command: sudo docker rm -f streaming_server
    sudo: yes
  - name: Build the server docker
    command: sudo docker build -t streaming_server streaming_benchmark/docker_server
    sudo: yes
  - name: Run the server docker
    command: sudo docker run -d -t --net=host -v /streaming_server:/streaming_server --privileged=true --name=streaming_server streaming_server
    sudo: yes

- hosts: clients
  tasks:
  - name: Remove docker container named streaming_client if it exists
    command: sudo docker rm -f streaming_client
    sudo: yes
  - name: Build the client docker
    command: sudo docker build -t streaming_client streaming_benchmark/docker_client
    sudo: yes
  - name: Run the client docker
    command: sudo docker run -d -t --net=host -v /streaming_client:/streaming_client --privileged=true --name=streaming_client streaming_client
    sudo: yes
  - name: Install the kernel sources
    apt: pkg=linux-source state=present update_cache=yes
    sudo: yes
  - name: Get the dummynet code
    git: repo=https://github.com/luigirizzo/dummynet.git dest=dummynet
  - name: Build dummynet
    command: chdir=dummynet make
  - name: Install dummynet
    command: chdir=dummynet cp ipfw/ipfw /usr/sbin/ipfw
    sudo: yes
  - name: Load dummynet
    command: insmod dummynet/kipfw-mod/ipfw_mod.ko
    sudo: yes
    ignore_errors: yes
  - name: Set client bandwidth limits
    command: streaming_benchmark/run_limit_bw.sh {{if}} {{ips}}
    sudo: yes
