---
- hosts: videoclients
  vars:
    num_clients_per_machine: 4
    log_file_name1: cl-240p-50-10000-10-20-00.log			# The names of the log files generated on the server and copied over to the client
    log_file_name2: cl-360p-50-4000-10-20-00.log
    log_file_name3: cl-480p-50-1600-10-20-00.log
    log_file_name4: cl-720p-50-800-10-20-00.log
    # Path of the directory that contains the Httperf logs copied over from the server machine
    server_shared_dir: ~/shared_dir
    max_num_sessions: 1000						# The max value for the binary search to find the maximum throughput.
    min_num_sessions: 200						# The min value for the binary search to find the maximum throughput.
    server_ip: 10.22.17.31						# The server ip and port

  tasks:
  - name: Copy over the httperf logs
    copy: src="{{server_shared_dir}}/filegen/{{log_file_name1}}" dest=~/shared_dir/
  - name: Copy the httperf logs into the container
    command: docker cp /benchmarking/filegen/{{log_file_name1}} client_docker:/streaming_source/httperf
    
  - name: Copy over the httperf logs
    copy: src="{{server_shared_dir}}/filegen/{{log_file_name2}}" dest=~/shared_dir/
  - name: Copy the httperf logs into the container
    command: docker cp /benchmarking/filegen/{{log_file_name2}} client_docker:/streaming_source/httperf

  - name: Copy over the httperf logs
    copy: src="{{server_shared_dir}}/filegen/{{log_file_name3}}" dest=~/shared_dir/
  - name: Copy the httperf logs into the container
    command: docker cp /benchmarking/filegen/{{log_file_name3}} client_docker:/streaming_source/httperf

  - name: Copy over the httperf logs
    copy: src="{{server_shared_dir}}/filegen/{{log_file_name4}}" dest=~/shared_dir/
  - name: Copy the httperf logs into the container
    command: docker cp /benchmarking/filegen/{{log_file_name4}} client_docker:/streaming_source/httperf

  - name: Clone the binary search repository
    git: repo=https://github.com/taptipalit/hunter.git dest=./peak_hunting

  - name: Start the peak hunting algorithm
    local_action: ./peak_hunting/launch_hunt_bin.sh host_list.txt {{num_clients_per_machine}} {{server_ip}} {{log_file_name1}} {{log_file_name2}} {{log_file_name3}} {{log_file_name4}} {{server_shared_dir}} {{ansible_ssh_user}} {{min_num_sessions}} {{max_num_sessions}}


