---
- hosts: videoclients
  vars:
    log_file_name1: cl-240p-50-10000-10-20-00.log			# The names of the log files generated on the server and copied over to the client
    log_file_name2: cl-360p-50-4000-10-20-00.log
    log_file_name3: cl-480p-50-1600-10-20-00.log
    log_file_name4: cl-720p-50-800-10-20-00.log
    # Path of the directory that contains the Httperf logs copied over from the server machine
    server_shared_dir: /var/services/homes/tpalit/projects/benchmarking/docker_containers/video_streaming/tmp
    #max_num_sessions: 1000						# The max value for the binary search to find the maximum throughput.
    #min_num_sessions: 200						# The min value for the binary search to find the maximum throughput.
    #server_ip: 10.22.17.31						# The server ip and port
    #server_port: 80
#    local_ip: 10.22.17.31

  tasks:
  - name: Checkout the httperf repository 
    git: repo=https://github.com/taptipalit/videoperf.git dest=/benchmarking/httperf
  - name: Configure httperf 
    command: chdir=/benchmarking/httperf ./configure
  - name: Make httperf
    command: chdir=/benchmarking/httperf make
  - name: Create the filegen directory
    file: path=/benchmarking/filegen state=directory

  - name: Copy over the httperf logs
    copy: src="{{server_shared_dir}}/filegen/{{log_file_name1}}" dest=/benchmarking/filegen/
  - name: Copy over the httperf logs
    copy: src="{{server_shared_dir}}/filegen/{{log_file_name2}}" dest=/benchmarking/filegen/
  - name: Copy over the httperf logs
    copy: src="{{server_shared_dir}}/filegen/{{log_file_name3}}" dest=/benchmarking/filegen/
  - name: Copy over the httperf logs
    copy: src="{{server_shared_dir}}/filegen/{{log_file_name4}}" dest=/benchmarking/filegen/


