---
- hosts: clients
  vars:
    streaming_client_dir: /streaming_client
    num_clients_per_machine: 4
    server_ip: 10.22.17.31
    log_file_name1: cl-720p-10-800-10-5-00.log
    log_file_name2: cl-480p-10-1600-10-5-00.log
    log_file_name3: cl-360p-10-4000-10-5-00.log
    log_file_name4: cl-240p-10-10000-10-5-00.log
    min_num_sessions: 100
    max_num_sessions: 1000
  tasks:
  - name: Copy logs to client
    synchronize: src=./logs/ dest={{streaming_client_dir}}/logs/
    sudo: yes
  - name: Add client to host list
    local_action: shell echo "{{inventory_hostname}} {{ip_alias1}} {{ip_alias2}} {{ip_alias3}} {{ip_alias4}}" >> client.hostlist
  - name: Clone the binary search repository
    local_action: git repo=https://github.com/taptipalit/hunter.git dest=./peak_hunting update=no
  - name: Copy over the host_list.txt
    local_action: copy src=client.hostlist dest=./peak_hunting/

# ./launch_hunt_bin.sh client.hostlist 3 10.22.17.31 /streaming_client/logs/cl-720p-10-800-10-5-00.log  /streaming_client/logs/cl-480p-10-1600-10-5-00.log /streaming_client/logs/cl-360p-10-4000-10-5-00.log /streaming_client/logs/cl-240p-10-10000-10-5-00.log /streaming_client tpalit 10 1000
  - name: Start the peak hunting algorithm
    local_action: command chdir=./peak_hunting ./launch_hunt_bin.sh client.hostlist {{num_clients_per_machine}} {{server_ip}} {{streaming_client_dir}}/logs/{{log_file_name1}} {{streaming_client_dir}}/logs/{{log_file_name2}} {{streaming_client_dir}}/logs/{{log_file_name3}} {{streaming_client_dir}}/logs/{{log_file_name4}} {{streaming_client_dir}} {{ansible_ssh_user}} {{min_num_sessions}} {{max_num_sessions}}
